"""The macro registry: every quantity the manuscript may quote, as
\\newcommand lines.

Macro names are LaTeX control sequences, i.e. letters only: digits are
spelled out (`token("1a") -> "OneA"`), methods map through METHOD_TOKENS
(`mc3 -> McThree`). `Registry.write()` emits results_macros.tex
(header says it is generated; entries sorted by name so diffs are stable)
and results_macros.json (name -> value / raw / source, for audits).
Duplicate names raise: a number must have exactly one origin.
"""

from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

NAME_RE = re.compile(r"^[A-Za-z]+$")
HEADER = ("% AUTO-GENERATED by scripts/99_results_macros.py — DO NOT EDIT.\n"
          "% Every number here is read from finished pipeline outputs\n"
          "% (reports/paper/*.json); rerun scripts/99_results_macros.py.\n")

DIGIT_WORDS = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
               "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}

METHOD_TOKENS = {
    "susie": "Susie", "hierNet": "HierNet", "glinternet": "Glinternet",
    "lasso": "Lasso",
    "stability": "Stability", "stability_refit": "StabilityRefit",
    "exact": "Exact",
    "mc3": "McThree",   # the MCMC sampler's rows
}


def token(s: str) -> str:
    """Any label -> a letters-only CamelCase token: '1a' -> 'OneA',
    'n_bin 30-199' -> 'NBinThreeZeroOneNineNine', 'f=0.15' -> 'FZeroOneFive'."""
    if s in METHOD_TOKENS:
        return METHOD_TOKENS[s]
    out: list[str] = []
    new_word = True
    for ch in s:
        if ch.isdigit():
            out.append(DIGIT_WORDS[ch])
            new_word = True
        elif ch.isalpha():
            out.append(ch.upper() if new_word else ch)
            new_word = False
        else:
            new_word = True
    tok = "".join(out)
    if not tok:
        raise ValueError(f"no letters or digits in {s!r}")
    return tok


def name(*parts: str) -> str:
    """Join tokens into a macro name: name('ip', 'Auc', 'susie', 'mx')
    -> 'ipAucSusieMx' (first part keeps its case)."""
    if not parts:
        raise ValueError("empty macro name")
    head, *rest = parts
    n = head + "".join(token(p) for p in rest)
    if not NAME_RE.match(n):
        raise ValueError(f"invalid macro name {n!r}")
    return n


@dataclass(frozen=True)
class Macro:
    name: str
    value: str
    raw: Any
    source: str


class Registry:
    def __init__(self) -> None:
        self._items: dict[str, Macro] = {}

    def add(self, name: str, value: str, raw: Any = None, source: str = "") -> None:
        if not NAME_RE.match(name):
            raise ValueError(f"macro name must be letters only: {name!r}")
        if name in self._items:
            raise KeyError(f"duplicate macro {name!r} (from {self._items[name].source!r})")
        self._items[name] = Macro(name, str(value), _jsonable(raw), source)

    def __len__(self) -> int:
        return len(self._items)

    def __contains__(self, name: str) -> bool:
        return name in self._items

    def __getitem__(self, name: str) -> Macro:
        return self._items[name]

    def items(self) -> list[Macro]:
        return [self._items[k] for k in sorted(self._items)]

    def tex(self) -> str:
        lines = [HEADER]
        for m in self.items():
            lines.append(f"\\newcommand{{\\{m.name}}}{{{m.value}}}\n")
        return "".join(lines)

    def write(self, tex_path: Path, json_path: Path | None = None) -> None:
        tex_path.parent.mkdir(parents=True, exist_ok=True)
        tex_path.write_text(self.tex())
        if json_path is not None:
            json_path.write_text(json.dumps({m.name: asdict(m) for m in self.items()},
                                            indent=1, sort_keys=True) + "\n")


def _jsonable(x: Any) -> Any:
    """numpy scalars/arrays -> plain python for the JSON audit file."""
    if hasattr(x, "tolist"):
        return x.tolist()
    if hasattr(x, "item"):
        return x.item()
    return x
