"""LaTeX (booktabs) table writer. Cells arrive already formatted by
pipeline.style; this module only lays them out and escapes labels.
"""

from __future__ import annotations

from pathlib import Path

from pipeline.style import tex_escape

HEADER = "% AUTO-GENERATED by scripts/80_tables.py — DO NOT EDIT.\n"
MISSING = "--"   # what pipeline.style prints for an absent number


def latex_table(header: list[str], rows: list[list[str]], align: str | None = None,
                caption: str | None = None, label: str | None = None,
                escape_cells: bool = False, note: str | None = None,
                full_width: bool = False, resize: bool = False) -> str:
    """`full_width` stretches the table across \\textwidth with `tabular*` and
    stretchy inter-column glue, which fills the text block without rescaling the
    type the way \\resizebox would, and needs no extra package. `resize` scales
    the tabular (not the note) to \\linewidth with graphicx's \\resizebox: only
    for a table whose natural width exceeds the text block, since it also
    enlarges a narrow one."""
    ncol = len(header)
    align = align or ("l" + "r" * (ncol - 1))
    lines = [HEADER]
    if caption is not None:
        lines += ["\\begin{table}[t]", "\\centering", "\\small"]
    env = "tabular*" if full_width else "tabular"
    if resize:
        lines.append("\\resizebox{\\linewidth}{!}{%")
    if full_width:
        align = align[:1] + "@{\\extracolsep{\\fill}}" + align[1:]
        lines.append(f"\\begin{{{env}}}{{\\textwidth}}{{{align}}}")
    else:
        lines.append(f"\\begin{{{env}}}{{{align}}}")
    lines.append("\\toprule")
    lines.append(" & ".join(tex_escape(h) for h in header) + " \\\\")
    lines.append("\\midrule")
    for row in rows:
        # a lone rule or spacing command is written as its own line, not as a row
        if len(row) == 1 and row[0].startswith(("\\midrule", "\\addlinespace")):
            lines.append(row[0])
            continue
        cells = [tex_escape(str(c)) if escape_cells else str(c) for c in row]
        lines.append(" & ".join(cells) + " \\\\")
    lines.append("\\bottomrule")
    lines.append(f"\\end{{{env}}}")
    if resize:
        lines.append("}")
    if note:
        lines.append(f"\\par\\smallskip\\footnotesize {note}")
    if caption is not None:
        lines.append(f"\\caption{{{caption}}}")
        if label:
            lines.append(f"\\label{{{label}}}")
        lines.append("\\end{table}")
    return "\n".join(lines) + "\n"


def bold_best(heads: list[str], values: list[float | None], direction: str) -> list[str]:
    """Bold the best formatted cell head of one comparison group.

    `heads` are cells already formatted by `pipeline.style`, `values` the raw
    numbers behind them (None for a cell that does not take part: a missing
    number, or a row measured on other hardware). `direction` is "max" or
    "min". A tie is a tie AT THE PRINTED PRECISION: every cell whose head
    renders exactly like the winner's is bolded too, because bolding one of
    two cells that read "0.0416" would claim a difference the table does not
    show. Only the head is wrapped, so a compound cell keeps its bracket
    outside the bold: pass "0.774" and append " [0.667, 1.000]" afterwards.
    """
    if direction not in ("max", "min"):
        raise ValueError(f"direction must be 'max' or 'min', not {direction!r}")
    live = [(i, v) for i, v in enumerate(values)
            if v is not None and v == v and heads[i] != MISSING]
    if not live:
        return list(heads)
    winner = (max if direction == "max" else min)(live, key=lambda iv: iv[1])[0]
    out = list(heads)
    for i, _ in live:
        if heads[i] == heads[winner]:
            out[i] = f"\\textbf{{{out[i]}}}"
    return out


def write(path: Path | str, text: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return path
